### ISSUE TITLE
Hello, do you know how to solve this problem

### ISSUE THREAD

**Issue by bubbleqi** [ugurcanozalp/multilingual-ner#1]
![图片](https://user-images.githubusercontent.com/37301736/116056309-3c3cbb00-a6b0-11eb-90ad-3b404fee6364.png)

**Comment by ugurcanozalp** [comment]
As far as i see, you should install NLTK's punkt package from a python command as proposed in last 2 lines of the error. Our tokenizer uses this for sentence splitting. I am now adding those commands into setup.py but you still need to do this if you don't install package.
